### ISSUE TITLE
find an error when make csim-target

### ISSUE THREAD

**Issue by muguang123** [UCLA-VAST/minimap2-acceleration#2]
there is a fatal error: CL/cl_ext_xilinx.h: No such file or directory when I make the Makefile by HLS version. There is an solution I found in Xilinx Community https://forums.xilinx.com/t5/SDAccel/CL-CL-ext-xilinx-h-could-not-be-found/td-p/904240 ,but still not suit me. There is anynoe meet the problem.

**Comment by dotkrnl** [comment]
This header file is shipped with Xilinx Runtime (XRT). Please make sure that you have installed it correctly. Besides, please make sure you are using an SDAccel version that supports XRT (I guess that means 2018.3+).

**Comment by muguang123** [comment]
> This header file is shipped with Xilinx Runtime (XRT). Please make sure that you have installed it correctly. Besides, please make sure you are using an SDAccel version that supports XRT (I guess that means 2018.3+).

Thank you for your reply, I found an error occurred when I install XRT 2018.3 and now I am trying to install the XRT correctly
